version: '3'
services:
  db:
    build:
      context: .
      dockerfile: Dockerfiledb
    ports:
    - "5003:3306"
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
    - "5001:80"
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile    
    ports:
    - "5002:5002"
    restart: always
    