version: '3'
services:
  db:
    image: mysql:5.7
    ports:
    - "5003:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    environment:
      MYSQL_ROOT_PASSWORD: dev-root
      MYSQL_USER: dev-user
      MYSQL_PASSWORD: dev-password
      MYSQL_DATABASE: ProyectoFinalDra
    restart: on-failure

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
    - "5001:80"
    restart: on-failure

 # app:
  #  build:
   #   context: .
    #  dockerfile: Dockerfile    
   # ports:
    #- "5002:5002"
    