version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile    
    ports:
    - "80:80"
    restart: always
    command:
      bash -c "ng serve --host 0.0.0.0 --port 80 --disable-host-check"
    