version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile    
    ports:
    - "4200:4200"
    command:
      bash -c "ng serve --host 0.0.0.0 --port 4200 --disable-host-check"
    